version: "3.9"

services:
  mysql:
    container_name: mysql_testing
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      - "3306:3306"

  php-fpm:
    container_name: php-fpm_testing
    build:
      context: ./php-fpm
    volumes:
      - ./../:/var/www
    restart: always
    ports:
      - "3000:3000"

  nginx:
    container_name: nginx_testing
    build:
      context: ./nginx
    volumes:
      - ./../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/environment/local/sites/:/etc/nginx/sites-available
      - ./nginx/environment/local/conf.d/:/etc/nginx/conf.d
    # - ./logs:/var/log
    depends_on:
      - php-fpm
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      default:
        ipv4_address: 178.62.254.38

networks:
  default:
    external:
      name: custom_net
